# Generated by Django 4.0.3 on 2022-04-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('cor', models.CharField(max_length=20)),
            ],
        ),
    ]
