# Generated by Django 4.0.3 on 2022-04-03 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos_api', '0002_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='categoria',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='videos_api.categoria'),
            preserve_default=False,
        ),
    ]
